/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package shein_proj;

/* Feito por ...
João Pedro Flausino */ 
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

public class JCad_Produto extends javax.swing.JFrame {
    private static JCad_Produto JCad_Produto_Unico;
    private static Connection connection;
    /**
     * Creates new form JCad_produto
     */
    public JCad_Produto(Connection connection) {
        
        this.connection = connection;
        initComponents();
        fetchData();
    }
    
    private void fetchData() {
        String query = "SELECT * FROM Produto";
        try (PreparedStatement statement = connection.prepareStatement(query);
             ResultSet resultSet = statement.executeQuery()) {
            
             DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
             model.setRowCount(0);

            // Iterate over the result set and add rows to the table model
            while (resultSet.next()) {
                int id = resultSet.getInt("id_produto");
                String name = resultSet.getString("nome_pro");
                String categoria = resultSet.getString("categoria_pro");
                float preco = resultSet.getFloat("preco");
                int quant = resultSet.getInt("quantidade_estoque");

                model.addRow(new Object[]{id, name, categoria, preco, quant});
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    public static JCad_Produto getJCad_Produto(Connection connection){
        if (JCad_Produto_Unico == null){
            JCad_Produto_Unico = new JCad_Produto(connection);
        }
        return JCad_Produto_Unico;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        categoria_txt = new javax.swing.JTextField();
        Excluir_btn = new javax.swing.JButton();
        produto_txt = new javax.swing.JTextField();
        preco_txt = new javax.swing.JTextField();
        Salvar_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Editar_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        quantidade_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(34, 40, 49));
        jPanel1.setPreferredSize(new java.awt.Dimension(660, 380));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "produto", "categoria", "preço", "quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        categoria_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoria_txtActionPerformed(evt);
            }
        });

        Excluir_btn.setText("Excluir");
        Excluir_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Excluir_btnActionPerformed(evt);
            }
        });

        produto_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produto_txtActionPerformed(evt);
            }
        });

        preco_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preco_txtActionPerformed(evt);
            }
        });

        Salvar_btn.setText("Salvar");
        Salvar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salvar_btnActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("produto");

        Editar_btn.setText("Editar");
        Editar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Editar_btnActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("preço");

        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("Categoria");

        quantidade_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantidade_txtActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setText("quantidade");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(produto_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(categoria_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(preco_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(quantidade_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Salvar_btn)
                        .addGap(18, 18, 18)
                        .addComponent(Excluir_btn)
                        .addGap(18, 18, 18)
                        .addComponent(Editar_btn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(produto_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(categoria_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(preco_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quantidade_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Salvar_btn)
                    .addComponent(Excluir_btn)
                    .addComponent(Editar_btn))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void produto_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produto_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_produto_txtActionPerformed

    private void categoria_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoria_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoria_txtActionPerformed

    private void preco_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preco_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_preco_txtActionPerformed

    private void Salvar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salvar_btnActionPerformed
        // TODO add your handling code here:
        String query = "INSERT INTO produto (id_produto, nome_pro, categoria_pro, preco, quantidade_estoque) " +
        "VALUES (DEFAULT,?, ?, ?, ?)";
        try (PreparedStatement statement = connection.prepareStatement(query)) {
            String produto_texto,categoria_texto ;
            int quantidade_texto;
            float preco_texto;
            produto_texto = produto_txt.getText();
            categoria_texto = categoria_txt.getText();
            preco_texto = Float.parseFloat(preco_txt.getText());
            quantidade_texto = Integer.parseInt(quantidade_txt.getText());
            statement.setString(1, produto_texto);
            statement.setString(2, categoria_texto);
            statement.setFloat(3, preco_texto);
            statement.setInt(4, quantidade_texto);
            

            statement.executeUpdate();
            
            
            JOptionPane.showMessageDialog(null, "Added product !! ");
            
            fetchData();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error adding client: " + ex.getMessage());
        }
    }//GEN-LAST:event_Salvar_btnActionPerformed

    private void Excluir_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Excluir_btnActionPerformed
        // TODO add your handling code here:       
            String query = "DELETE FROM Produto WHERE id_produto = ?";
        try (PreparedStatement statement = connection.prepareStatement(query)) {
            int id = Integer.parseInt(JOptionPane.showInputDialog("Enter product ID to delete:"));
            statement.setInt(1, id);

            int rowsAffected = statement.executeUpdate();
            
            fetchData();
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null,"Product deleted successfully");
            } else {
                JOptionPane.showMessageDialog(null,"Product not found");
            }
        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error deleting product: " + ex.getMessage());
        }
    }//GEN-LAST:event_Excluir_btnActionPerformed

    private void Editar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Editar_btnActionPerformed
        // TODO add your handling code here:
        String query = "UPDATE produto SET nome_pro = ?, categoria_pro = ?, preco = ?, quantidade_estoque = ? WHERE id_produto = ?";
        
        try(PreparedStatement statement = connection.prepareStatement(query)){
            int id = Integer.parseInt(JOptionPane.showInputDialog("Enter product ID:"));
            String produto_texto,categoria_texto ;
            int quantidade_texto;
            float preco_texto;
            produto_texto = produto_txt.getText();
            categoria_texto = categoria_txt.getText();
            preco_texto = Float.parseFloat(preco_txt.getText());
            quantidade_texto = Integer.parseInt(quantidade_txt.getText());
            
            statement.setString(1, produto_texto);
            statement.setString(2, categoria_texto);
            statement.setFloat(3, preco_texto);
            statement.setInt(4, quantidade_texto);
            statement.setInt(5, id);
            
            statement.executeUpdate();
            JOptionPane.showMessageDialog(null, "Product Updated !! ");
            
             fetchData();

        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error updating client: " + ex.getMessage());
        }
    }//GEN-LAST:event_Editar_btnActionPerformed

    private void quantidade_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantidade_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantidade_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JCad_Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JCad_Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JCad_Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JCad_Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JCad_Produto(connection).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Editar_btn;
    private javax.swing.JButton Excluir_btn;
    private javax.swing.JButton Salvar_btn;
    private javax.swing.JTextField categoria_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField preco_txt;
    private javax.swing.JTextField produto_txt;
    private javax.swing.JTextField quantidade_txt;
    // End of variables declaration//GEN-END:variables
}
