/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package shein_proj;

/* Feito por ...
João Pedro Flausino */ 
import java.sql.Connection;
import java.sql.Date;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.util.regex.Pattern;

public class JCad_Pedido extends javax.swing.JFrame {
    
    private static JCad_Pedido JCad_Pedido_Unico;
    private static Connection connection;

    /**
     * Creates new form JCad_pedido
     */
    public JCad_Pedido(Connection connection) {
        this.connection = connection;
        initComponents();
        fetchData();
    }
    
     private void fetchData() {
        String query = """
                       SELECT id_pedido,id_cliente,data_pedido, calcularTotalPedido(id_pedido) AS total_calculado
                       FROM Pedido;""";
        try (PreparedStatement statement = connection.prepareStatement(query);
             ResultSet resultSet = statement.executeQuery()) {
            
             DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
             model.setRowCount(0);

            // Iterate over the result set and add rows to the table model
            while (resultSet.next()) {
                int id_produto = resultSet.getInt("id_pedido");
                int id_cliente = resultSet.getInt("id_cliente");
                Date data = resultSet.getDate("data_pedido");
                float total = resultSet.getFloat("total_calculado");

                model.addRow(new Object[]{id_produto, id_cliente, data, total});
                System.out.println(model);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    public static JCad_Pedido getJCad_Pedido(Connection connection){
        if (JCad_Pedido_Unico == null){
            JCad_Pedido_Unico = new JCad_Pedido(connection); 
        }
        return JCad_Pedido_Unico;    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        Excluir_btn = new javax.swing.JButton();
        Salvar_btn = new javax.swing.JButton();
        ID_Cliente_txt = new javax.swing.JTextField();
        Editar_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Data_pedido_txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(32767, 32767));

        jPanel1.setBackground(new java.awt.Color(34, 40, 49));
        jPanel1.setPreferredSize(new java.awt.Dimension(660, 380));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "ID Cliente", "Data do Pedido", "Total do Pedido"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("Data do Pedido");

        Excluir_btn.setText("Excluir");
        Excluir_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Excluir_btnActionPerformed(evt);
            }
        });

        Salvar_btn.setText("Salvar");
        Salvar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salvar_btnActionPerformed(evt);
            }
        });

        ID_Cliente_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_Cliente_txtActionPerformed(evt);
            }
        });

        Editar_btn.setText("Editar");
        Editar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Editar_btnActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("ID do Cliente");

        Data_pedido_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Data_pedido_txtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ID_Cliente_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Data_pedido_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Salvar_btn)
                        .addGap(18, 18, 18)
                        .addComponent(Excluir_btn)
                        .addGap(18, 18, 18)
                        .addComponent(Editar_btn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ID_Cliente_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Data_pedido_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Salvar_btn)
                    .addComponent(Excluir_btn)
                    .addComponent(Editar_btn))
                .addGap(61, 61, 61))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ID_Cliente_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_Cliente_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_Cliente_txtActionPerformed

    private void Data_pedido_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Data_pedido_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Data_pedido_txtActionPerformed

    private void Salvar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salvar_btnActionPerformed
        // TODO add your handling code here:
        String query = "INSERT INTO pedido (id_pedido, id_cliente, data_pedido) " +
        "VALUES (DEFAULT,?, ?)";
        try (PreparedStatement statement = connection.prepareStatement(query)) {
            String data_pedido_texto, padrão_regex_data ;
            int id_cliente_texto;
            id_cliente_texto = Integer.parseInt(ID_Cliente_txt.getText());
            data_pedido_texto = Data_pedido_txt.getText();
            
            padrão_regex_data = "\\d{4}-\\d{2}-\\d{2}";
            
            boolean validar_data = Pattern.matches(padrão_regex_data, data_pedido_texto);
            
            if(validar_data){
                statement.setInt(1, id_cliente_texto);
                statement.setString(2, data_pedido_texto);

                statement.executeUpdate();

                JOptionPane.showMessageDialog(null, "Added order !! ");
                
                fetchData();
            }else{
                JOptionPane.showMessageDialog(null, "Error adding client: incorrect data");
            }
            

           
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error adding client: " + ex.getMessage());
        }
    }//GEN-LAST:event_Salvar_btnActionPerformed

    private void Excluir_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Excluir_btnActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(JOptionPane.showInputDialog("Enter client ID to delete:"));
        String query = "DELETE FROM Pedido WHERE id_pedido = ?";
        try (PreparedStatement statement = connection.prepareStatement(query)) {
            statement.setInt(1, id);

            int rowsAffected = statement.executeUpdate();
            fetchData();
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null,"Order deleted successfully");
            } else {
                JOptionPane.showMessageDialog(null, "Order not found");
            }
        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error deleting client: " + ex.getMessage());
            
            
         
        }
    }//GEN-LAST:event_Excluir_btnActionPerformed

    private void Editar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Editar_btnActionPerformed
        // TODO add your handling code here:
        String query = "UPDATE pedido SET id_cliente = ?, data_pedido = ? WHERE id_pedido = ?";
        
        try(PreparedStatement statement = connection.prepareStatement(query)){
            int id = Integer.parseInt(JOptionPane.showInputDialog("Enter order ID:"));
            String data_pedido_texto, padrão_regex_data ;
            int id_cliente_texto;
            id_cliente_texto = Integer.parseInt(ID_Cliente_txt.getText());
            data_pedido_texto = Data_pedido_txt.getText();
            
            padrão_regex_data = "\\d{4}-\\d{2}-\\d{2}";
            
            boolean validar_data = Pattern.matches(padrão_regex_data, data_pedido_texto);
            
            if(validar_data){
                statement.setInt(1, id_cliente_texto);
                statement.setString(2, data_pedido_texto);
                statement.setInt(3,id);

                statement.executeUpdate();

                JOptionPane.showMessageDialog(null, "Order Updated !! ");
                
                fetchData();
            }else{
                JOptionPane.showMessageDialog(null, "Error adding client: incorrect data");
            }
            
            statement.executeUpdate();

        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error updating client: " + ex.getMessage());
        }
    }//GEN-LAST:event_Editar_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JCad_Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JCad_Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JCad_Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JCad_Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JCad_Pedido(connection).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Data_pedido_txt;
    private javax.swing.JButton Editar_btn;
    private javax.swing.JButton Excluir_btn;
    private javax.swing.JTextField ID_Cliente_txt;
    private javax.swing.JButton Salvar_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
