/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package shein_proj;


/* Feito por ...
João Pedro Flausino*/ 

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class JCad_Item_pedido extends javax.swing.JFrame {
    private static JCad_Item_pedido JCad_Item_pedido_unico;
    private static Connection connection;
    
    /**
     * Creates new form JCad_Item_pedido
     */
    public JCad_Item_pedido(Connection connection) {
        this.connection = connection;
        initComponents();
        fetchData();
    }
    
    
    
    private void fetchData() {
        String query_itempedido = """
                                  SELECT ItemPedido.id_item, ItemPedido.id_pedido, ItemPedido.id_produto, ItemPedido.quantidade_prod, ItemPedido.preco_dataC, Produto.nome_pro
                                  FROM ItemPedido
                                  JOIN Produto ON ItemPedido.id_produto = Produto.id_produto;""";
        String query_produto = "SELECT id_produto,nome_pro FROM produto";
        String query_ID_cliente = "SELECT id_cliente FROM cliente";
        
        try (PreparedStatement statement = connection.prepareStatement(query_itempedido);
             ResultSet resultSet = statement.executeQuery()) {
            
             DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
             model.setRowCount(0);

            // Iterate over the result set and add rows to the table model
            while (resultSet.next()) {
                int id_produto = resultSet.getInt("id_item");
                int id_pedido= resultSet.getInt("id_pedido");
                String nome_produto = resultSet.getString("nome_pro");
                int id_prod = resultSet.getInt("id_produto");
                int quantidade_compra = resultSet.getInt("quantidade_prod");
                float preco_compra = resultSet.getFloat("preco_dataC");

                model.addRow(new Object[]{id_produto, id_pedido,nome_produto, id_prod,quantidade_compra, preco_compra});
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        try (PreparedStatement statement = connection.prepareStatement(query_ID_cliente);
             ResultSet resultSet = statement.executeQuery()) {
            while (resultSet.next()) {
                String productName = resultSet.getString("id_cliente");
                jComboBox_ID.addItem(productName);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        
        try (PreparedStatement statement = connection.prepareStatement(query_produto);
             ResultSet resultSet = statement.executeQuery()) {
            while (resultSet.next()) {
                int productId = resultSet.getInt("id_produto");
                String productName = resultSet.getString("nome_pro");
                ProductItem productItem = new ProductItem(productId, productName);
                
                jComboBox_produto.addItem(productItem);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    public static JCad_Item_pedido getJCad__item_pedido(Connection connection){
        if (JCad_Item_pedido_unico == null){
            JCad_Item_pedido_unico = new JCad_Item_pedido(connection); 
        }
        return JCad_Item_pedido_unico;    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Excluir_btn = new javax.swing.JButton();
        Salvar_btn = new javax.swing.JButton();
        Editar_btn = new javax.swing.JButton();
        jComboBox_ID = new javax.swing.JComboBox<>();
        jComboBox_produto = new javax.swing.JComboBox<>();
        jSpinner1 = new javax.swing.JSpinner();
        jTextField_preco = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(34, 40, 49));
        jPanel1.setPreferredSize(new java.awt.Dimension(660, 380));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID_item", "ID do pedido", "nome do produto", "ID do produto", "Quantidade", "Preço do item"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Excluir_btn.setText("Excluir");
        Excluir_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Excluir_btnActionPerformed(evt);
            }
        });

        Salvar_btn.setText("Salvar");
        Salvar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salvar_btnActionPerformed(evt);
            }
        });

        Editar_btn.setText("Editar");
        Editar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Editar_btnActionPerformed(evt);
            }
        });

        jComboBox_ID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        jComboBox_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_IDActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("ID do produto");

        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("ID do pedido");

        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("quantidade");

        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setText("preço do produto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_produto, 0, 113, Short.MAX_VALUE)
                    .addComponent(jTextField_preco))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Salvar_btn)
                        .addGap(18, 18, 18)
                        .addComponent(Excluir_btn)
                        .addGap(18, 18, 18)
                        .addComponent(Editar_btn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Salvar_btn)
                    .addComponent(Excluir_btn)
                    .addComponent(Editar_btn))
                .addGap(61, 61, 61))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Editar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Editar_btnActionPerformed
        // TODO add your handling code here:
        String query = "UPDATE itempedido SET id_pedido = ?,id_produto = ?, quantidade_prod = ?,preco_dataC = ? WHERE id_item = ?";

        try(PreparedStatement statement = connection.prepareStatement(query)){
            int id_item = Integer.parseInt(JOptionPane.showInputDialog("Enter order ID:"));
            int id_pedido_dropdown = Integer.parseInt((String) jComboBox_ID.getSelectedItem());
            ProductItem produto_dropdown = (ProductItem) jComboBox_produto.getSelectedItem();
            int selectedQuantity = (int) jSpinner1.getValue();
            float preco = Float.parseFloat(jTextField_preco.getText());
            
            int selectedId = produto_dropdown.getId();
            String selectedName = produto_dropdown.getName();
            
            statement.setInt(1, id_pedido_dropdown);
            statement.setInt(2, selectedId);
            statement.setInt(3,selectedQuantity);
            statement.setFloat(4, preco);
            statement.setInt(5,id_item);

            statement.executeUpdate();

            JOptionPane.showMessageDialog(null, "item Updated !! ");

            fetchData();

            statement.executeUpdate();

        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error updating client: " + ex.getMessage());
        }
    }//GEN-LAST:event_Editar_btnActionPerformed

    private void Excluir_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Excluir_btnActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(JOptionPane.showInputDialog("Enter client ID to delete:"));
        String query = "DELETE FROM itempedido WHERE id_item = ?";
        try (PreparedStatement statement = connection.prepareStatement(query)) {
            statement.setInt(1, id);

            int rowsAffected = statement.executeUpdate();
            fetchData();
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null,"Order deleted successfully");
            } else {
                JOptionPane.showMessageDialog(null, "Order not found");
            }
        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error deleting client: " + ex.getMessage());

        }
    }//GEN-LAST:event_Excluir_btnActionPerformed

    private void Salvar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salvar_btnActionPerformed
        // TODO add your handling code here:
        String query = "INSERT INTO itempedido (id_item,id_pedido, id_produto, quantidade_prod,preco_dataC) " +
        "VALUES (DEFAULT,?, ?,?,?)";
        try (PreparedStatement statement = connection.prepareStatement(query)) {
            int id_pedido_dropdown = Integer.parseInt((String) jComboBox_ID.getSelectedItem());
            ProductItem produto_dropdown = (ProductItem) jComboBox_produto.getSelectedItem();
            int selectedQuantity = (int) jSpinner1.getValue();
            float preco = Float.parseFloat(jTextField_preco.getText());
            
            int selectedId = produto_dropdown.getId();
            String selectedName = produto_dropdown.getName();
            
            
            statement.setInt(1, id_pedido_dropdown);
            statement.setInt(2, selectedId);
            statement.setInt(3, selectedQuantity);
            statement.setFloat(4, preco);

            statement.executeUpdate();

                JOptionPane.showMessageDialog(null, "Added item  !! ");

                fetchData();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error adding client: " + ex.getMessage());
        }
    }//GEN-LAST:event_Salvar_btnActionPerformed

    private void jComboBox_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_IDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JCad_Item_pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JCad_Item_pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JCad_Item_pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JCad_Item_pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JCad_Item_pedido(connection).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Editar_btn;
    private javax.swing.JButton Excluir_btn;
    private javax.swing.JButton Salvar_btn;
    private javax.swing.JComboBox<String> jComboBox_ID;
    private javax.swing.JComboBox<ProductItem> jComboBox_produto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_preco;
    // End of variables declaration//GEN-END:variables
}
